apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: primeiroreplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-replicaset
  template:
    metadata:
      labels:
        app: nginx-replicaset
    spec:
      containers:
      - name: nginx
        image: nginx