apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: devopspro
  labels:
    app: nginx
    versao: beta
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80